### ISSUE TITLE
the error screen is displayed after login

### ISSUE THREAD

**Issue by zzpmaster** [moneytree/moneytree-link-ios-sdk#12]
I'm using authMode is PKCE. iOS Version is 6.3.0。

After logging in, an error screen appears, As for this phenomenon, where am i missing setting? 

thanks for help me.

<img width="332" alt="Screen Shot 2022-11-04 at 13 49 36" src="https://user-images.githubusercontent.com/1327089/199900669-b47ca5eb-0996-43e9-90bb-6d6f350329a0.png">

**Comment by awe-mt** [comment]
Thank you for your question!

Can you provide the details of what method you are using to open the login screen? Also, can you share what you you have set in your `MTLConfiguration` object?

**Comment by zzpmaster** [comment]
@awe-mt 
thanks for your help.

The following code
```
let configuration = MTLConfiguration()
configuration.environment = .staging
configuration.scopes = [
            MTLClientScopeGuestRead,
            MTLClientScopeAccountsRead,
            MTLClientScopeTransactionsRead
]
let mtLinkClient = MTLinkClient(configuration: configuration)
```

I need to set any other values？

**Comment by awe-mt** [comment]
Thank you. We will investigate and try to get back to you early next week.

**Comment by zzpmaster** [comment]
@awe-mt 
Hi team, 
Do you have any progress?

**Comment by mt-erik** [comment]
@zzpmaster We have updated a misconfiguration for your client and you should be able to login with the SDK. Could you please try again? Thank you.

**Comment by mt-erik** [comment]
@zzpmaster We have updated a misconfiguration for your client and now you should be able to login with the SDK. Could you please try again? Thank you!

**Comment by zzpmaster** [comment]
@awe-mt 
Thanks so much!
After clicking the login button, it keeps showing the loading icon.  After dozens of seconds, the loading icon disappears and the page does not jump. Need to update the SDK？

<img width="335" alt="Screen Shot 2022-11-09 at 16 44 30" src="https://user-images.githubusercontent.com/1327089/200784300-9b75c2b7-4e9b-4577-b8d0-d5f4ee55aa46.png">

**Comment by mt-erik** [comment]
@zzpmaster With the configuration of the SDK you previously shared, I could not reproduce this problem. Is this still happening on your side?

**Comment by zzpmaster** [comment]
@mt-erik 
it works very well. Thanks so much!  Worked like a charm. You are a legend.
